services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgresql"
    ports:
      - "5050:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "3000:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
